package generic_Utilities;

import java.lang.reflect.Method;
import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Listeners;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.aventstack.extentreports.reporter.configuration.Theme;

import objectRepository.LoginPage;
import objectRepository.WelcomePage;

@Listeners(generic_Utilities.ListenersImplementation.class)
public class BaseTest {

    public WebDriver driver;
    public ExtentReports reports;
    public static ExtentTest test;
    
    @BeforeSuite
    public void configureReport() {
        ExtentSparkReporter spark=new ExtentSparkReporter("./src/test/resources/reports/DWS_Report_"+Java_Utility.getName()+".html");
		
		reports=new ExtentReports();
		spark.config().setReportName("DWS Report");
		spark.config().setTheme(Theme.DARK);
		spark.config().setDocumentTitle("Generated by Moni");
		reports.attachReporter(spark);
    }
    
    
	
	@BeforeClass
	public void openBrowser() {
		
		
		System.setProperty("webdriver.edge.driver","./drivers/msedgedriver.exe");
		driver=new EdgeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));
		driver.get(File_Utility.getPropertyData("url"));
		
	}
	
	
	@BeforeMethod
	public void loginToDWS(Method method) {
		
		test=reports.createTest(method.getName());
		WelcomePage wp = new WelcomePage(driver);
		wp.getLoginLink().click();
		LoginPage lp = new LoginPage(driver);
		lp.getEmailTF().sendKeys(File_Utility.getPropertyData("email"));
		lp.getPassTF().sendKeys(File_Utility.getPropertyData("password"));
		lp.getLoginButton().click();
		test.log(Status.INFO,"User Logged in successfully");
		
	}
	
	@AfterMethod
	public void logoutFromDWS() {
		
		
		driver.findElement(By.linkText("Log out")).click();
		test.log(Status.INFO,"User Logged out in successfully");
		
	}
	
	@AfterSuite
	public void closeBrowser() {
		reports.flush();
		driver.quit();
		test.log(Status.INFO,"Browser closed successfully");
	}
	

}
